imports:
    - { resource: 'parameters.yml' }

parameters:
  db:
    url: mysql://%db_config.user%:%db_config.password%@%db_config.host%/%db_config.database%
  configPath: %basePath%/config
  logPath: %basePath%/log

services:
  minify:
    class: IngoWalther\ImageMinifyApi\Minify\Minify
    arguments: [@fileHandler, @logger]

  mozJpegCompressor:
    class: IngoWalther\ImageMinifyApi\Compressor\MozJpegCompressor
    tags:
        - { name: image.compressor, alias: jpeg}

  pngquantCompressor:
    class: IngoWalther\ImageMinifyApi\Compressor\PngquantCompressor
    tags:
        - { name: image.compressor, alias: png}

  svgoCompressor:
    class: IngoWalther\ImageMinifyApi\Compressor\SVGOCompressor
    tags:
        - { name: image.compressor, alias: svgo}

  gifsicleCompressor:
    class: IngoWalther\ImageMinifyApi\Compressor\GifsicleCompressor
    tags:
        - { name: image.compressor, alias: gif}

  fileHandler:
    class: IngoWalther\ImageMinifyApi\File\FileHandler

  randomStringGenerator:
    class: IngoWalther\ImageMinifyApi\Security\RandomStringGenerator

  apiKeyCheck:
    class: IngoWalther\ImageMinifyApi\Security\ApiKeyCheck
    arguments: [@userRepository]

  apiKeyGenerator:
    class: IngoWalther\ImageMinifyApi\Security\ApiKeyGenerator
    arguments: [@userRepository, @randomStringGenerator]

  userRepository:
    class: IngoWalther\ImageMinifyApi\Database\UserRepository
    arguments: [@dbConnection]

  dbConfig:
    class: Doctrine\DBAL\Configuration

  dbConnection:
    class: Doctrine\DBAL\Connection
    factory_class: Doctrine\DBAL\DriverManager
    factory_method: getConnection
    arguments: [%db%, @dbConfig]

  errorHandler:
    class: IngoWalther\ImageMinifyApi\Error\ErrorHandler
    arguments: [@logger]

  logger:
    class: Monolog\Logger
    arguments: ['ImageMinifyApi']
    calls:
      - [pushHandler, [@logHandler]]

  logHandler:
    class: Monolog\Handler\RotatingFileHandler
    arguments: [%logPath%/app.log, 7]

  console:
    class: Symfony\Component\Console\Application

  addUserCommand:
    class: IngoWalther\ImageMinifyApi\Command\AddUserCommand
    calls:
      - [setApiKeyGenerator, [@apiKeyGenerator]]
    tags:
      - { name: console.command, alias: user}

  listUserCommand:
    class: IngoWalther\ImageMinifyApi\Command\ListUserCommand
    calls:
      - [setUserRepository, [@userRepository]]
    tags:
      - { name: console.command, alias: listUser}

  setupCommand:
    class: IngoWalther\ImageMinifyApi\Command\SetupCommand
    calls:
      - [setConnection, [@dbConnection]]
      - [setConfigPath, [%configPath%]]
    tags:
      - { name: console.command, alias: setup}
